name: Deploy TalkPick Server

on:
  push:
    branches:
      - deploy/127  # for test

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: âœ”ï¸ GIT - Checkout Repository âœ”ï¸
        uses: actions/checkout@v4

      - name: ğŸ”» SETUP - Install JDK 21 ğŸ”»
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: ğŸ”— CONFIG - Create application.yml ğŸ”—
        run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > ./src/main/resources/application.yml

      - name: ğŸ”— CONFIG - Create .env ğŸ”—
        run: |
          touch .env
          echo '${{ secrets.ENV }}' >> .env

      - name: â³ BUILD - Run Test & Build JAR â³
        run: ./gradlew clean build

      - name: â˜ï¸ CONFIG - Configure AWS Credentials â˜ï¸
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: â˜ï¸ AWS - Login to Amazon ECR â˜ï¸
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: ğŸ³ DOCKER - Build Docker Image ğŸ³
        run: docker build -t talkpick-server .

      - name: ğŸ³ DOCKER - Tag Docker Image ğŸ³
        run: docker tag talkpick-server ${{ steps.login-ecr.outputs.registry }}/talkpick-server:latest

      - name: â˜ï¸ AWS - Push Docker Image to ECR â˜ï¸
        run: docker push ${{ steps.login-ecr.outputs.registry }}/talkpick-server:latest

      - name: ğŸ› ï¸ PERMISSIONS - Fix file ownership and permission before tar
        run: |
          sudo chown -R $(whoami):$(whoami) .
          chmod -R 755 scripts
          chmod 644 docker-compose.yml

      - name: â˜ï¸ AWS - Compress for CodeDeploy â˜ï¸
        run: tar -czvf $GITHUB_SHA.tar.gz appspec.yml scripts docker-compose.yml

      - name: â˜ï¸ AWS - Upload Archive to S3 â˜ï¸
        run: aws s3 cp --region ap-northeast-2 ./$GITHUB_SHA.tar.gz s3://talkpick-server/$GITHUB_SHA.tar.gz

      - name: â˜ï¸ AWS - Create Deployment to EC2 â˜ï¸
        run: |
          aws deploy create-deployment \
            --application-name talkpick-server \
            --deployment-config-name CodeDeployDefault.AllAtOnce \
            --deployment-group-name Production \
            --s3-location "bucket=talkpick-server,bundleType=tgz,key=$GITHUB_SHA.tar.gz"